apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: l0f9ex9y9-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: l0f9ex9y9-python 
  name: l0f9ex9y9-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: l0f9ex9y9-python 
