apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: l0f9ex9y9-python 
  janus-idp.io/tekton: l0f9ex9y9-python
  backstage.io/kubernetes-id: l0f9ex9y9-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: l0f9ex9y9-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml